apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  tasks:
    - name: pipeline-hello-task
      taskRef:
        name: hello-task
    - name: pipeline-source-to-image-task
      taskRef: 
        name: source-to-image-task