apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  resources:
    - name: git-source
      type: git
  tasks:
  - name: pipeline-hello-task
    taskRef:
      name: hello-task
  - name: pipeline-source-to-image-task
    serviceAccountName: docker-auth
    taskRef:
      name: source-to-image-task
    resources:
      inputs:
        - name: git-source
          resource: git-source