apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-task
spec:
  inputs:
    resources:
      - name: docker-source
        type: git
    params:
      - name: pathToDockerFile
        type: string 
        description: path to dockerfile
        default: /workspace/docker-source/dockerfile
      - name: pathToContext
        type: string
        description: path to context
        default: /workspace/docker-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: executor
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=${outputs.resources.builtImage.url}
		- --context=$(inputs.params.pathToContext)
      env:
	  - name: DOCKER_CONFIG
        value: /tekton/home/.docker/