apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-task
spec:
  inputs:
    resources:
      - name: src
        type: git
    params:
      - name: imageUrl
        description: Url of image repository
        default: remkohdev/spring-boot-app
      - name: imageTag
        type: string
        description: Tag to apply to the built image
        default: 1.0.0
      - name: pathToDockerFile
        description: The path to the dockerfile to build (relative to the context)
        default: Dockerfile
      - name: pathToContext
        description:
          The path to the build context
      - default: .
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: executor
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
      - --dockerfile=${inputs.params.pathToDockerFile}
      - --destination=${outputs.resources.builtImage.url}
      - --context=/workspace/src/${inputs.params.pathToContext}