apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-task
spec:
  outputs:
    resources:
      - name: builtImage
        type: image
        params:
        - name: url
          value: docker.io/remkohdev/spring-boot-app:1.0.0
  steps:
    - name: executor
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
      - --destination=${outputs.resources.builtImage.url}