apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-task
spec:
  inputs:
    resources:
      - name: gitsource
        type: git
    params:
	  - name: pathToContext
        type: string
        description: The path to the build context, used by Kaniko - within the workspace
        default: /workspace/gitsource/
	  - name: pathToDockerFile
        type: string
        description: The path to the dockerfile to build (relative to the context)
        default: /workspace/gitsource/Dockerfile
      - name: imageUrl
        description: Url of image repository
        default: remkohdev/spring-boot-app
	  - name: imageTag
        type: string
        description: Tag to apply to the built image
        default: latest
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)
        - --context=/workspace/gitsource/$(inputs.params.pathToContext)