apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: hello-task
spec:
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
      - "hello world"
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: source-to-image-task
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToDockerFile
      description: The path to the dockerfile to build (relative to the context)
      default: Dockerfile
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag to apply to the built image
      default: "latest"
    steps:
      - name: build-and-push
        image: gcr.io/kaniko-project/executor
        command:
          - /kaniko/executor
        args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(inputs.params.imageUrl):$(inputs.params.imageTag)
        - --context=/workspace/git-source/$(inputs.params.pathToContext)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-using-kubectl-task
spec:
  inputs:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Url of image repository
    - name: imageTag
      description: Tag of the images to be used.
      default: "latest"
  steps:
    - name: update-yaml
      image: alpine
      command: ["sed"]
      args:
      - "-i"
      - "-e"
      - "s;__IMAGE__;$(inputs.params.imageUrl):$(inputs.params.imageTag);g"
      - "/workspace/git-source/$(inputs.params.pathToYamlFile)"
    - name: run-kubectl
      image: lachlanevenson/k8s-kubectl
      command: ["kubectl"]
      args:
      - "apply"
      - "-f"
      - "/workspace/git-source/$(inputs.params.pathToYamlFile)"